name: Production

on:
  push:
    branches: 
      - master
      - feature/*

jobs:
  Production-Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: 18

      - run: npm install

      - name: Build Next.js project
        env:
          NEXT_PUBLIC_API_URL: https://api-nail-art.miever.net
        run: npm run build

      - uses: wlixcc/SFTP-Deploy-Action@v1.0 
        with:  
          username: 'ubuntu'
          server: '${{ secrets.SERVER_IP }}'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          local_path: './out/*'
          remote_path: '/home/ubuntu/nail-art'